### ISSUE TITLE
SparkFun nRF24LU1+ breakout board

### ISSUE THREAD

**Issue by jgamblin** [RFStorm/mousejack#1]
The SparkFun nRF24LU1+ breakout board is retired.  Is there a replacement board that will work? 

https://www.sparkfun.com/products/retired/9034

**Comment by marcnewlin** [comment]
The [CrazyRadio PA](https://wiki.bitcraze.io/projects:crazyradiopa:index) dongle works well, and is available from a number of vendors online. 

I've only tested against the CrazyRadio PA and the SparkFun breakout board, but the firmware should work on any 32kB nRF24LU1+ based dongle or breakout board.

It should also work on 16kB variants, but the bootloader address would need to be updated to 0x3800 from 0x7800. (The Nordic bootloader occupies the top 2kB of memory.) 

https://github.com/RFStorm/mousejack/blob/master/src/usb.h#L23
