### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Knwn** [RFStorm/mousejack#10]
root@kali:/home/mousejack-master# make install 
./prog/usb-flasher/usb-flash.py bin/dongle.bin
[2016-03-07 21:29:23.468]  Looking for a compatible device that can jump to the Nordic bootloader
[2016-03-07 21:29:23.505]  Looking for a device running the Nordic bootloader
[2016-03-07 21:29:23.546]  Writing image to flash
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 99, in <module>
    dongle.read(0x81, 64, usb_timeout)
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 659, in read
    intf.bInterfaceNumber,
AttributeError: 'NoneType' object has no attribute 'bInterfaceNumber'
Makefile:25: recipe for target 'install' failed
## make: **\* [install] Error 1

Any ideas? Thanks!

_Edit_
-Debian 4.9.2-10
-updated Crazyradio PA

**Comment by marcnewlin** [comment]
There are a few things to try with troubleshooting this. 
1. It's possible there is a functionality difference with the version of PyUSB on your machine . I'd first try updating it as follows. 
   
   `sudo pip install -U -I pip && sudo pip install -U -I pyusb`
2. It looks like you're running as root, but in case you in fact aren't, try running the command with `sudo`.
3. If this isn't successful, then I would try using the flashing tool from the CrazyRadio firmware. To do this, you will need to change the USB ID from 1915:7777 to 1915:0102 here: 
   
   https://github.com/bitcraze/crazyradio-firmware/blob/master/usbtools/cradioFlasher.py#L207

Let me know how this works out.

**Comment by Knwn** [comment]
It turns out there was a problem with the pip install. After attempting to re-install a couple times with apt-get and continuous errors I gave up on apt-get and a simple download and install worked fine for me:

sudo apt-get remove python-pip
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py

Thanks!
