### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by haxorthematrix** [RFStorm/mousejack#3]
On first run after installing dependencies, the make fails. It is resolved by doing a "mkdir bin/", but unfortunately after that the make fails a second time:

~/mousejack$ make
sdcc --model-large --std-c99 -c src/main.c -o bin/main.rel
src/usb.h:23: error 78: incompatible types
from type 'void function    ( )  literal-code\* '
to type 'void function    ( )  xdata-code\* '
src/main.c:39: error 78: incompatible types
from type 'void function    ( )  literal-code\* '
to type 'void function    ( )  xdata-const-code\* '
make: **\* [main.rel] Error 1

**Comment by marcnewlin** [comment]
What OS and version of SDCC are you using?

**Comment by zer0pwned** [comment]
`myheart@ubuntu:~$ cat /proc/version
Linux version 3.13.0-32-generic (buildd@phianna) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #57~precise1-Ubuntu SMP Tue Jul 15 03:51:20 UTC 2014
myheart@ubuntu:~$ sdcc --version
SDCC : mcs51/gbz80/z80/avr/ds390/pic16/pic14/TININative/xa51/ds400/hc08 2.9.0 #5416 (Feb  3 2010) (UNIX)`

ubuntu 12.04.5

got the same error info, what version of SDCC do you use?

@marcnewlin

**Comment by haxorthematrix** [comment]
$ cat /proc/version
Linux version 3.2.0-99-generic-pae (buildd@lgw01-31) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #139-Ubuntu SMP Mon Feb 1 23:43:25 UTC 2016

$ sdcc --version
SDCC : mcs51/gbz80/z80/avr/ds390/pic16/pic14/TININative/xa51/ds400/hc08 2.9.0 #5416 (Feb  3 2010) (UNIX)

$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise

I find the "12.04" odd, in that before starting the install I did a dist-upgrade followed by a reboot...

**Comment by marcnewlin** [comment]
@haxorthematrix @niklaus520 

I bet it's an SDCC version issue. I'm using SDCC 3.3.0 (and haven't tested on prior versions of SDCC).

```
 % sdcc -v
SDCC : mcs51/gbz80/z80/z180/r2k/r3ka/ds390/pic16/pic14/TININative/ds400/hc08/s08 3.3.0 #8604 (Dec 30 2013) (Linux)
111
```

I'll see if I can track down the minimum version and update the makefile to check for it.

**Comment by haxorthematrix** [comment]
Ok, I'm going to make sure that my dist-upgrade actually finished and see if there is a newer version of SDCC in the repositories. If not, I'll figure out how to make sure I have >= 3.3.0 and report back.

**Comment by marcnewlin** [comment]
It looks like the minimum version of SDCC is 3.1.0. I updated the readme to reflect this, and added a version check in the makefile.
