### ISSUE TITLE
ProductID:002b

### ISSUE THREAD

**Issue by icebob** [RFStorm/mousejack#6]
Hello,

I have an nRF24LU1 from [Ali](http://www.aliexpress.com/item/NRF24LU1-NRF24LU1P-2-4G-Wireless-Transceiver-USB-Module-Wireless-Module-NEW/32294020974.html).
But Usb flasher didn't find, because the productID is 002b.

```
lsusb
...
Bus 001 Device 005: ID 1915:002b Nordic Semiconductor ASA
```

Can I use this board?

**Comment by marcnewlin** [comment]
@icebob 

It looks like this is a 16kB variant of the nRF24LU1+. I haven't tested with this variant, but it **should** work. The firmware occupies less than 5kB of flash memory, so there shouldn't be any issues there. 

The Nordic bootloader occupies the top 2kB of flash memory, and the firmware has the address hardcoded at address 0x7800 for the 32kB variant. 

To use the firmware with a 16kB variant, you will want to change this to 0x3800 here: 

https://github.com/RFStorm/mousejack/blob/master/src/usb.h#L23

Additionally, you will need to update this line in the Makefile from 0x8000 to 0x4000: 

https://github.com/RFStorm/mousejack/blob/master/Makefile#L3

Finally, you will need to update the product ID in usb-flash.py to 0x002B:

https://github.com/RFStorm/mousejack/blob/master/prog/usb-flasher/usb-flash.py#L81

Given that I haven't tested on a 16kB variant of the nRF24LU1+ I can't say with complete confidence that you won't brick your dongle. If you do, you can always re-flash the board over SPI using the Teensy flasher code with a Teensy 3.1/3.2 (and likely other Arduino variants as well). 

Let me know if this works for you!

**Comment by icebob** [comment]
Thank you. I made these changes and trying again with make, make install, but now I got "Resource busy" error message. (I plugged the board to a Raspberry Pi 2)

```
pi@raspberrypi ~/mousejack $ sudo make install
./prog/usb-flasher/usb-flash.py bin/dongle.bin
[2016-02-28 19:18:13.590]  Looking for a compatible device that can jump to the Nordic bootloader
[2016-02-28 19:18:13.759]  Looking for a device running the Nordic bootloader
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 82, in <module>
    dongle.set_configuration()
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
Makefile:25: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by icebob** [comment]
dmesg says OS want to use the board as a USB HID keyboard.

```
[ 5387.098564] usb 1-1.3: new full-speed USB device number 6 using dwc_otg
[ 5387.213855] usb 1-1.3: New USB device found, idVendor=1915, idProduct=002b
[ 5387.213876] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5387.213888] usb 1-1.3: Product: Nordic Semiconductor nRFready Basic Remote Dongle
[ 5387.213900] usb 1-1.3: Manufacturer: Nordic Semiconductor
[ 5387.213911] usb 1-1.3: SerialNumber: \xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf\xffffffef\xffffffbf\xffffffbf\xffffffbf\xffffffbf
[ 5387.233186] input: Nordic Semiconductor Nordic Semiconductor nRFready Basic Remote Dongle as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:1915:002B.0002/input/input1
[ 5387.290448] hid-generic 0003:1915:002B.0002: input,hiddev0,hidraw0: USB HID v1.11 Keyboard [Nordic Semiconductor Nordic Semiconductor nRFready Basic Remote Dongle] on usb-3f980000.usb-1.3/input0

```

**Comment by marcnewlin** [comment]
It sounds like your dongle shipped with something other than the default Nordic bootloader, so I think your best option would be to flash it over SPI. There are a couple options I am aware of to do so.
- the [Teensy flasher](https://github.com/RFStorm/mousejack/tree/master/prog/teensy-flasher) utility in this repository. 
- the [JTAGkey or BusPirate flashing options](https://wiki.bitcraze.io/projects:crazyradio:spi_programming) detailed in the CrazyRadio PA project

**Comment by icebob** [comment]
I don't have Teensy. Can I flashing with an Arduino Uno too?

**Comment by marcnewlin** [comment]
I have only tested the SPI flashing code with a Teensy, but it uses the regular Android SPI library, so it should work with an Uno as well.

**Comment by shebang42** [comment]
Thanks, Marc!   I've got the same board, and it has indeed 16k flash.  With the above hints I got it running.
I flashed it with with a buspirate, using 'flasher.pl' of buspirate_nrf24lu1p .

**Comment by TotalDay** [comment]
Used Arduino Nano to the ISP. Plug the dongle as a scheme. Changed everything as it was described, as well as PID: VID in the script for the Teensy - to flash 25 minutes, nothing.

**Comment by TotalDay** [comment]
[16kb_USB_dongle_Hex.zip](https://github.com/RFStorm/mousejack/files/299716/16kb_USB_dongle_Hex.zip)

**Comment by TotalDay** [comment]
![nrf24lu1pinout](https://cloud.githubusercontent.com/assets/13989990/15811431/286715d2-2bb1-11e6-9b8d-8a068fe1a848.jpg)

Вот схема донгла

**Comment by TotalDay** [comment]
![nanopdf](https://cloud.githubusercontent.com/assets/13989990/15811434/45f8b90c-2bb1-11e6-90d1-8954be67905d.png)
Вот схема Arduino Nano

нужны 4 контакта
SCN
CSN
MOSI
MISO

и 2 контакта 
GND
VCC 3.3

Из описаня SPI для Ардуино Нано, больше не надо, но на донгле есть PROG - я его никуда не подключал

**Comment by TotalDay** [comment]
Прошится не получилось через Ардуино Нано. У кого есть какие идеи?

**Comment by TotalDay** [comment]
shebang42, can your share your *.hex and *.bin files?

**Comment by TotalDay** [comment]
![4](https://cloud.githubusercontent.com/assets/13989990/15830643/41c3f72c-2c22-11e6-84b7-bc4bebdab54d.png)
![3](https://cloud.githubusercontent.com/assets/13989990/15830641/41c0857e-2c22-11e6-96ee-77b2570eae73.png)
![2](https://cloud.githubusercontent.com/assets/13989990/15830644/41c4a06e-2c22-11e6-9a1f-8eb0df5abf63.png)
![1](https://cloud.githubusercontent.com/assets/13989990/15830642/41c3f4de-2c22-11e6-8a38-82b865444836.png)

Надоело все и прошился прямо в Винде таким [программатором для этих чипов](http://ali.pub/k8xg1), сходил к другу и взял. Все прошилось, видно ASCII прошивки в донгле, но винда не может считать PID\VID устройства и дрова не садятся, линукс тоже не видит, наверно когда собирал HEX прошивку, там PID и VID у меня другой или еще что.

Tired of all and sew straight in Windows so [programmer for these chips](http://ali.pub/k8xg1), went to a friend and took it. All I ask to be seen ASCII firmware inside the dongle, but Windows can not find the PID \ VID device, Linux also does not see too, probably when compiling HEX firmware with wrong PID and VID I have a different or something.

**Comment by TotalDay** [comment]
[NRFLasher.zip](https://github.com/RFStorm/mousejack/files/300951/NRFLasher.zip)

**Comment by dpavlin** [comment]
Just another datapoint: I have same board with same usb id which has v2.0 printed on it, and this one is 32k part (so you don't have to patch source for it). Hopefully, this will save some time to someone else.

As a side-note, I'm unable to enter usb boot loader mode after flashing this stick. I have no idea why.

**Comment by DRCRecoveryData** [comment]
> Hello,
> 
> I have an nRF24LU1 from [Ali](http://www.aliexpress.com/item/NRF24LU1-NRF24LU1P-2-4G-Wireless-Transceiver-USB-Module-Wireless-Module-NEW/32294020974.html).
> But Usb flasher didn't find, because the productID is 002b.
> 
> ```
> lsusb
> ...
> Bus 001 Device 005: ID 1915:002b Nordic Semiconductor ASA
> ```
> 
> Can I use this board?
> 

check my post:

I think i solved all issue in here of signed bootloader:

https://twitter.com/drcrecovery/status/1671590705238781953?s=46
