### ISSUE TITLE
Question: Will disabling the "Microsoft Hardware USB Mouse" via Device Manager help?

### ISSUE THREAD

**Issue by i68040** [RFStorm/mousejack#9]
I noticed that it is possible to disable the USB Mouse functionality of the Sculpt dongle via the Microsoft Windows 'Device Manager'. Would this mitigate the attack? I only use the MS Keyboard, so I wouldn't mind disabling the mouse functionality if it means I can get my keyboard back. :)

**Comment by marcnewlin** [comment]
I haven't tried this, but it certainly sounds possible. I will do a test next week and see if it is an effective mitigation technique.

**Comment by i68040** [comment]
Thanks, I really appreciate it!

**Comment by i68040** [comment]
Just want to check in on this: were you able to run the test? I'm investigating alternate keyboards in case my suggestion is not an effective mitigation. :)

**Comment by marcnewlin** [comment]
@i68040, thank you for your patience. I tested disabling the 'Microsoft Hardware USB Mouse' device entry from a Microsoft Sculpt Ergonomic Desktop dongle, and was still able to successfully inject keystrokes. 

![mouse-properties](https://cloud.githubusercontent.com/assets/1245470/14045345/d30a086c-f26f-11e5-9816-b0a4b6c0cba5.png)

![notepad](https://cloud.githubusercontent.com/assets/1245470/14045346/d882637a-f26f-11e5-9a7e-4f6f6a055cc7.png)
